### ISSUE TITLE
Additional text of "IP Address" when setting IP on server 01/02.

### ISSUE THREAD

**Issue by MarkerMarked** [shgandhi/networkinglab470#1]
Command should be 

sudo ifconfig eth1 10.12.2.2/24 

for example for server 01.

![screen shot 2018-04-04 at 7 03 30 pm](https://user-images.githubusercontent.com/38054634/38339195-02392b28-383b-11e8-9686-d90f0557880a.png)

**Comment by shgandhi** [comment]
Thanks for pointing out. It has been corrected now.
