### ISSUE TITLE
Error when running vagrant up server01 leaf01 leaf02 spine01 spine02

### ISSUE THREAD

**Issue by aowhite** [shgandhi/networkinglab470#10]
When entering "vagrant up server01 leaf01 leaf02 spine01 spine02" I get the folllowing:

> Bringing machine 'server01' up with 'virtualbox' provider...
> Bringing machine 'leaf01' up with 'virtualbox' provider...
> Bringing machine 'leaf02' up with 'virtualbox' provider...
> Bringing machine 'spine01' up with 'virtualbox' provider...
> Bringing machine 'spine02' up with 'virtualbox' provider...
> ==> server01: Checking if box 'yk0/ubuntu-xenial' is up to date...
> ==> server01: Machine already provisioned. Run `vagrant provision` or use the `--provision`
> ==> server01: flag to force provisioning. Provisioners marked to run always will still run.
> ==> leaf01: Checking if box 'CumulusCommunity/cumulus-vx' is up to date...
> ==> leaf01: Clearing any previously set forwarded ports...
> ==> leaf01: Fixed port collision for 22 => 2222. Now on port 2202.
> ==> leaf01: Clearing any previously set network interfaces...
> ==> leaf01: Preparing network interfaces based on configuration...
>     leaf01: Adapter 1: nat
>     leaf01: Adapter 2: intnet
>     leaf01: Adapter 3: intnet
>     leaf01: Adapter 4: intnet
>     leaf01: Adapter 5: intnet
>     leaf01: Adapter 6: intnet
>     leaf01: Adapter 7: intnet
>     leaf01: Adapter 8: intnet
>     leaf01: Adapter 9: intnet
>     leaf01: Adapter 10: intnet
>     leaf01: Adapter 11: intnet
>     leaf01: Adapter 12: intnet
> ==> leaf01: Forwarding ports...
>     leaf01: 22 (guest) => 2202 (host) (adapter 1)
> ==> leaf01: Running 'pre-boot' VM customizations...
> ==> leaf01: Booting VM...
> ==> leaf01: Waiting for machine to boot. This may take a few minutes...
>     leaf01: SSH address: 127.0.0.1:2202
>     leaf01: SSH username: vagrant
>     leaf01: SSH auth method: private key
> Timed out while waiting for the machine to boot. This means that
> Vagrant was unable to communicate with the guest machine within
> the configured ("config.vm.boot_timeout" value) time period.
> 
> If you look above, you should be able to see the error(s) that
> Vagrant had when attempting to connect to the machine. These errors
> are usually good hints as to what may be wrong.
> 
> If you're using a custom box, make sure that networking is properly
> working and you're able to connect to the machine. It is a common
> problem that networking isn't setup properly in these boxes.
> Verify that authentication configurations are also setup properly,
> as well.
> 
> If the box appears to be booting properly, you may want to increase
> the timeout ("config.vm.boot_timeout") value.

I tried to find the config.vm.boot_timeout file it mentions but haven't been able to find it in my folders. Otherwise I'm not sure what else to try.

**Comment by shgandhi** [comment]
Are you running the command from the  OSPF folder? If not go to the OSPF folder and run `vagrant reload`

**Comment by aowhite** [comment]
If by OSPF folder you mean the cldemo-vagrant folder then yes I tried running in that. I also tried `vagrant reload` but that also gave me a time out error message as I posted above.

**Comment by shgandhi** [comment]
No, not the cldemo-vagrant folder. Please see the three steps in [here](https://github.com/shgandhi/networkinglab470/tree/master/OSPF#setting-up-the-topology).

**Comment by aowhite** [comment]
Okay I see that I was following the topology instructions [here](https://github.com/CumulusNetworks/cldemo-vagrant/blob/master/documentation/windows/README.md) when I wasnt' supposed to. I tried the `vagrant reload` command in the OSPF folder but that gives me another error:

> PS C:\470_Lab\networkinglab470\OSPF> vagrant reload
> DIR: C:/470_Lab/networkinglab470/OSPF
> DIR: C:/470_Lab/networkinglab470/OSPF
> DIR: C:/470_Lab/networkinglab470/OSPF
> DIR: C:/470_Lab/networkinglab470/OSPF
> DIR: C:/470_Lab/networkinglab470/OSPF
> ==> router01: Checking if box 'CumulusCommunity/cumulus-vx' is up to date...
> Vagrant cannot forward the specified ports on this VM, since they
> would collide with some other application that is already listening
> on these ports. The forwarded port to 2201 is already in use
> on the host machine.
> 
> To fix this, modify your current project's Vagrantfile to use another
> port. Example, where '1234' would be replaced by a unique host port:
> 
>   config.vm.network :forwarded_port, guest: 22, host: 1234
> 
> Sometimes, Vagrant will attempt to auto-correct this for you. In this
> case, Vagrant was unable to. This is usually because the guest machine
> is in a state which doesn't allow modifying port forwarding. You could
> try 'vagrant reload' (equivalent of running a halt followed by an up)
> so vagrant can attempt to auto-correct this upon booting. Be warned
> that any unsaved work might be lost.

**Comment by aowhite** [comment]
I've uninstalled and reinstalled Vagrant and that fixed the error I said above but now when I enter `vagrant ssh router01` it asks for a password and I'm not sure what that is.

**Comment by shgandhi** [comment]
The password is `vagrant`

**Comment by aowhite** [comment]
I was able to set up the rest of it. Thank you.
