### ISSUE TITLE
Log off procedure. (more of a question than a problem)

### ISSUE THREAD

**Issue by RyanQuinnNCSU** [shgandhi/networkinglab470#11]
So I followed all of the instructions and after some painful debugging I was able to get it working. However I am still little confused about what to do when I am done with the instructions. Should I keep the devices running on virtual box or do I turn them off before closing? Also what is the difference between the putty terminal and the virtual box terminal?

**Comment by shgandhi** [comment]
- You can do a `vagrant halt` this will shut down the virtual machines. Before coming to the lab you must run `vagrant up` so all the machines are up when you are in the lab. 
- We don't need putty to ssh into the VMs, you run the command `vagrant ssh <device-name>` to ssh to the device.
