### ISSUE TITLE
shell provisioner error

### ISSUE THREAD

**Issue by jacob-bouren** [shgandhi/networkinglab470#6]
when issuing "vagrant up" I'm receiving 

"there are errors in the configuration of this machine: 
shell provisioner: 
*'path' for shell provisioner does not exist on the host system: C:/Users/jacob/networkinglab470/OSPF/helper_scripts/extra_switch_config.sh"" 

running this setup: 
VirtualBox 5.2.26
git 2.21.0
vagrant: 2.0.2

**Comment by jacob-bouren** [comment]
It looks like the Vagrantfile is looking for "helper_scripts" under OSPF which doesn't contain that folder. "helper_scripts" is on the same level as ./OSPF in the folder structure. I will copt the helper_scripts folder into OSPF and run

edit: it appears this worked

**Comment by shgandhi** [comment]
Great! Closing the issue.
