### ISSUE TITLE
Error running vagrant up on MAC OS

### ISSUE THREAD

**Issue by HenryChen34** [shgandhi/networkinglab470#9]
While running vagrant up I got the following error message:

There are errors in the configuration of this machine. Please fix
the following errors and try again:

shell provisioner:
* `path` for shell provisioner does not exist on the host system: /Users/apple/networkinglab470/OSPF/helper_scripts/extra_switch_config.sh

**Comment by shgandhi** [comment]
See the solution at [shell provisioner error](https://github.com/shgandhi/networkinglab470/issues/6).
